{
    'name': 'Subscription Draft Invoice',
    'version': '19.0.1.0.0',
    'summary': 'Keep subscription auto-invoices in draft state until manual review',
    'description': """
Subscription Draft Invoice
==========================
From Odoo 16 onwards, subscription invoices generated by the scheduled action
are automatically posted. This module restores the ability to keep them in
**Draft** state, configurable per Recurring Plan.

Features
--------
* New "Draft Invoicing" toggle on each Recurring Plan
* When enabled, the automatic invoice is created but **not posted**
* Works transparently alongside payment tokens and all other subscription flows
* Zero impact on plans that have the option disabled
    """,
    'author': 'Lógica Consultores 360',
    'website': 'https://www.logicaconsultores.com',
    'support': 'info@logicaconsultores.com',
    'category': 'Sales/Subscriptions',
    'sequence': 10,
    'depends': ['sale_subscription'],
    'data': [
        'views/sale_subscription_plan_views.xml',
    ],
    'images': ['static/description/banner.png'],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': False,
}
